# version: “3”
services:
  web:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/nginx-docker:/etc/nginx
      - /opt/nginx-docker/conf.d:/etc/nginx/conf.d
      - /opt/www:/opt/www
      - /var/log/nginx:/var/log/nginx
    restart: always
    #user: "nginx"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - 80:80
      - 443:443
      - 31159:11262
    configs:
      - source: nginx_config_v1 # 引用 config 名稱
        target: /etc/nginx/nginx.conf # 掛載到容器內的路徑
    networks:
      - webnet
    logging:
      driver: "json-file"
      options:
        max-size: "20MB"
        max-file: "19"
networks:
  webnet:
configs:
  nginx_config_v1:
    external: true
