version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: pritunldb
    hostname: pritunldb
    network_mode: bridge
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./db:/data/db 
    logging:
      driver: "json-file"
      options:
        max-size: "20MB"
        max-file: "19"

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    restart: always
    depends_on:
        - mongo
    network_mode: bridge
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    links:
      - mongo
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 1980:80
      - 443:443
      - 43808:43808/udp
    logging:
      driver: "json-file"
      options:
        max-size: "20MB"
        max-file: "19"
